kind: Service
apiVersion: v1
metadata:
  name: ${PROJECT_NAME}
spec:
  selector:
    app: ${PROJECT_NAME} # Targets 1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Targets 3
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${PROJECT_NAME}
  labels:
    app: ${PROJECT_NAME}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${PROJECT_NAME} # Targets 1
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME} # 1
    spec:
      containers:
        - name: ${PROJECT_NAME}
          image: gcr.io/${GOOGLE_PROJECT_ID}/${PROJECT_NAME}:${CIRCLE_SHA1}
          ports:
            - name: http
              containerPort: 8080 # 3
              protocol: TCP
  strategy:
    type: RollingUpdate # Already default
