kind: Service
apiVersion: v1
metadata:
  name: ${SERVICE_NAME}
spec:
  selector:
    app: ${SERVICE_NAME} # Targets 1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Targets 3
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${SERVICE_NAME}
  labels:
    app: ${SERVICE_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME} # 1
    spec:
      containers:
        - name: ${SERVICE_NAME}
          image: gcr.io/${GOOGLE_PROJECT_ID}/${SERVICE_NAME}:${CIRCLE_SHA1}
          ports:
            - name: http
              containerPort: 8080 # 3
              protocol: TCP
  strategy:
    type: RollingUpdate # Already default
